import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.scss";
import Header from "./components/layouts/header/Header";
import Welcome from "./components/layouts/body/welcome/Welcome";
import Sidebar from "./components/layouts/sidebar/Sidebar";
import Dashboard from "./components/layouts/body/dashboard/Dashboard";
import { useSelector } from "react-redux";
import authSlice from "../store/authSlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const auth  = useSelector((state) => state.auth);
  return (
    <>
      <Head>
        <title>Bridgeon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        {auth ? (
          <>
            <section className={styles.body_layout}>
              <Sidebar />
              <Dashboard />
            </section>
          </>
        ) : (
          <>
            <Welcome />
          </>
        )}
      </main>
    </>
  );
}
