import React, { useEffect } from "react";
import Dashboard from "./body/dashboard/Dashboard";
import Sidebar from "./sidebar/Sidebar";
import Header from "./header/Header";
import Welcome from "./body/welcome/Welcome";
import Head from "next/head";
import styles from "../../styles/Home.module.scss";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import { useMediaQuery } from "@mantine/hooks";

const RouteOnAuth = ({ children, incomingPage }) => {
  const auth = useSelector((state) => state.auth);
  const router = useRouter();

  useEffect(() => {
    //redirect to root path if user isn't there
    if (!auth && !router.route.includes("/auth/")) router.push("/");
  }, [auth]);

  return router.route.includes("/auth/") && !auth ? (
    <>{incomingPage}</>
  ) : (
    <>{children}</>
  );
};

const Layouts = ({ children }) => {
  const notCompatible = useMediaQuery("(min-width: 738px)");

  const auth = useSelector((state) => state.auth);

  return (
    <>
      <Head>
        <title>Bridgeon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {Changing layout on route changes} */}
      {notCompatible ? (
        <RouteOnAuth incomingPage={children}>
          <main className={styles.main}>
            <Header />
            {/* {authorized users only can asses dashboard} */}
            {auth ? (
              <>
                <section className={styles.body_layout}>
                  <Sidebar />
                  {children}
                </section>
              </>
            ) : (
              <>
                <Welcome />
              </>
            )}
          </main>
        </RouteOnAuth>
      ) : (
        <>
          <div
            style={{
              width: "100%",
              height: "100%",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <h1 style={{paddingRight:"10px"}}>{`This device resolution won't support please try from another device`}</h1>
          </div>
        </>
      )}
    </>
  );
};

export default Layouts;
