import React, { useEffect } from "react";
import Dashboard from "./body/dashboard/Dashboard";
import Sidebar from "./sidebar/Sidebar";
import Header from "./header/Header";
import Welcome from "./body/welcome/Welcome";
import Head from "next/head";
import styles from "../../styles/Home.module.scss";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
// import { useMediaQuery } from "@mui/material";

const RouteOnAuth = ({ children, incomingPage }) => {
  const auth = useSelector((state) => state.userReducer.auth);
  const router = useRouter();

  useEffect(() => {
    //redirect to root path if user isn't there
    if (!auth && !router.route.includes("/auth/")) router.push("/");
    if (auth && router.route.includes("/auth/")) router.push("/");
  }, [auth]);

  return router.route.includes("/auth/") && !auth ? (
    <>{incomingPage}</>
  ) : (
    <>{children}</>
  );
};

const Layouts = ({ children }) => {
  const auth = useSelector((state) => state.userReducer.auth);

  return (
    <>
      <Head>
        <title>Bridgeon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {Changing layout on route changes} */}

      <RouteOnAuth incomingPage={children}>
        <main className={styles.main}>
          {/* {authorized users only can asses dashboard} */}
          {auth ? (
            <>
              <section className={styles.layout}>
                <Sidebar />
                <div className={styles.body}>
                  <Header />
                  {children}
                </div>
              </section>
            </>
          ) : (
            <>
              <Welcome />
            </>
          )}
        </main>
      </RouteOnAuth>
    </>
  );
};

export default Layouts;
